### ISSUE TITLE
Punctuation embedded end php not colored

### ISSUE THREAD

**Issue by smlombardi** [Briles/gruvbox-atom#2]
![screen shot 2016-05-30 at 12 16 05 pm](https://cloud.githubusercontent.com/assets/835148/15654230/5beac800-2660-11e6-9722-d37f4fe17774.png)

Scopes at cursor:
text.html.php
meta.embedded.line.php
**punctuation.section.embedded.end.php**
source.php

**Comment by smlombardi** [comment]
Thanks.  Did you apm publish this yet?

**Comment by Briles** [comment]
Not yet. This will make it into the next release.
