### ISSUE TITLE
pug syntax

### ISSUE THREAD

**Issue by michaeldeboeve** [Briles/gruvbox-atom#4]
Hi, it seems some items in the pug syntax aren't highlighted
Gruvbox:
<img width="489" alt="screen shot 2016-06-13 at 06 57 41" src="https://cloud.githubusercontent.com/assets/980956/15997489/f96240b6-3134-11e6-8a16-5e06f051813e.png">
Nobber:
<img width="514" alt="screen shot 2016-06-13 at 07 02 43" src="https://cloud.githubusercontent.com/assets/980956/15997503/2b5c4364-3135-11e6-9e2d-9d0ea9f82927.png">

And is it possible for pug mixins to have a different color?
Gruvbox:
<img width="704" alt="screen shot 2016-06-13 at 06 59 52" src="https://cloud.githubusercontent.com/assets/980956/15997514/5c36a0d8-3135-11e6-8fef-414d6c04a16d.png">
Nobber:
<img width="723" alt="screen shot 2016-06-13 at 07 02 33" src="https://cloud.githubusercontent.com/assets/980956/15997515/62abedf6-3135-11e6-9a20-d4696104a916.png">

Besides, I love this theme!

**Comment by Briles** [comment]
Thanks for reporting these!

Pug mixins should now be colored aqua, which should offer better contrast against any possible mixin arguments.

These changes and more have made it into [1.2.3](https://github.com/Briles/gruvbox-atom/releases/tag/v1.2.3), so make sure to update.

**Comment by michaeldeboeve** [comment]
yes, thanks! Looking good :)
