### ISSUE TITLE
Command palette highlight

### ISSUE THREAD

**Issue by smlombardi** [Briles/gruvbox-atom#7]
Highlighted words are black instead.  This is with default One Dark UI theme.

![screen shot 2016-07-19 at 9 01 18 am](https://cloud.githubusercontent.com/assets/835148/16950691/88efee06-4d8f-11e6-860c-cd088a70aaee.png)

**Comment by Briles** [comment]
What version of Atom are you using?

It appears to be correctly colored in 1.9.0-beta0 with One Dark UI.

Could you have some styles overriding the default style? The selector is `.symbols-view .list-group .character-match`. Gruvbox doesn't color this selector.

![untitled-1](https://cloud.githubusercontent.com/assets/7333245/16970478/56259e7a-4dea-11e6-9782-965e9aeb64dd.png)

**Comment by smlombardi** [comment]
That's odd, after a restart it no longer does it.
