### ISSUE TITLE
Deprecated selector in `gruvbox-plus-syntax/index.less`

### ISSUE THREAD

**Issue by not7cd** [Briles/gruvbox-atom#9]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

http://pastebin.com/jirpRGjJ

**Comment by kiviok** [comment]
+1

**Comment by platinumsink** [comment]
I am getting this deprication warning also.

**Comment by kiviok** [comment]
@Briles please merge my pull request.
alternatively, guys, you can clone my fork and replacing `editor.less` and `language.less` in ~/.atom/packages/gruvbox-plus-syntax/styles/
